baseURL: https://qingran.netlify.app
languageCode: en-us
summaryLength: '10'
theme: kross-hugo
title: Qingran Zhang
params:
  address: London Business School, Regent's Park, NW1 4SA, London
  author: Qingran Zhang
  baidu_analytics_id: ''
  baidu_site_verification: ''
  contact:
    enable: yes
    form_action: '#'
  cookies:
    enable: yes
    expire_days: 2
  copyright: Copyright &copy; 2021 a Theme by [Gethugothemes](https://gethugothemes.com)
  description: This is meta description
  email: qzhang.mfa2022@london.edu
  google_analytics_id: ''
  home: Home
  logo: ''
  map:
    enable: yes
    gmap_api: https://maps.googleapis.com/maps/api/js?key=&#038;types=(cities)&#038;libraries=places&#038;language=en
    map_latitude: '51.509865'
    map_longitude: '-0.118092'
    map_marker: images/marker.png
  phone: +44 (0)756 314 0079
  plugins:
    css:
      - link: plugins/bootstrap/bootstrap.min.css
      - link: plugins/slick/slick.css
      - link: plugins/themify-icons/themify-icons.css
    js:
      - link: plugins/jQuery/jquery.min.js
      - link: plugins/bootstrap/bootstrap.min.js
      - link: plugins/slick/slick.min.js
      - link: plugins/shuffle/shuffle.min.js
      - link: plugins/google-map/map.js
  preloader:
    enable: yes
    preloader: images/preloader.gif
  social:
    - URL: '#'
      icon: ti-facebook
    - URL: 'https://www.instagram.com/raaan_zzz/?r=nametag'
      icon: ti-instagram
    - URL: '#'
      icon: ti-dribbble
    - URL: '#'
      icon: ti-twitter-alt
  theme_color: '#41228e'
menu:
  main:
    - URL: about
      name: About
      weight: 1
    - URL: portfolio
      name: Portfolio
      weight: 2
    - URL: contact
      name: Contact
      weight: 3
